# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: |
            (?x)(
                ^content/|
                ^i18n/|
            )
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
- repo: local
  hooks:
    - id: rustywind
      name: rustywind Tailwind CSS formatter
      language: node
      additional_dependencies:
        - rustywind@latest
      entry: rustywind
      args: ["--quiet", "--write", "./templates"]
